const foreign_booster = ["Spell Ruler"];

const boosters = [
  "Legend of Blue Eyes White Dragon",
  "Metal Raiders",
  "Magic Ruler",
  "Pharaoh's Servant",
  "Labyrinth of Nightmare",
  "Legacy of Darkness",
  "Pharaonic Guardian",
  "Magician's Force",
  "Dark Crisis",
  "Invasion of Chaos",
  "Ancient Sanctuary",
  "Soul of the Duelist",
  "Rise of Destiny",
  "Flaming Eternity",
  "The Lost Millennium",
  "Cybernetic Revolution",
  "Elemental Energy",
  "Shadow of Infinity",
  "Enemy of Justice",
  "Power of the Duelist",
  "Cyberdark Impact",
  "Strike of Neos",
  "Force of the Breaker",
  "Tactical Evolution",
  "Gladiator's Assault",
  "Phantom Darkness",
  "Light of Destruction",
  "The Duelist Genesis",
  "Crossroads of Chaos",
  "Crimson Crisis",
  "Raging Battle",
  "Ancient Prophecy",
  "Stardust Overdrive",
  "Absolute Powerforce",
  "The Shining Darkness",
  "Duelist Revolution",
  "Starstrike Blast",
  "Storm of Ragnarok",
  "Extreme Victory",
  "Generation Force",
  "Photon Shockwave",
  "Order of Chaos",
  "Galactic Overlord",
  "Return of the Duelist",
  "Abyss Rising",
  "Cosmo Blazer",
  "Lord of the Tachyon Galaxy",
  "Judgment of the Light",
  "Shadow Specters",
  "Legacy of the Valiant",
  "Primal Origin",
  "Duelist Alliance",
  "The New Challengers",
  "Secrets of Eternity",
  "Crossed Souls",
  "Clash of Rebellions",
  "Dimension of Chaos",
  "The Secret Forces",
  "High-Speed Riders",
  "Breakers of Shadow",
  "Wing Raiders",
  "Shining Victories",
  "The Dark Illusion",
  "Invasion: Vengeance",
  "Destiny Soldiers",
  "Raging Tempest",
  "Fusion Enforcers",
  "Maximum Crisis",
  "Pendulum Evolution",
  "Code of the Duelist",
  "Circuit Break",
  "Spirit Warriors",
  "Extreme Force",
  "Flames of Destruction",
  "Dark Saviors",
  "Cybernetic Horizon",
  "Shadows in Valhalla",
  "Soul Fusion",
  "Hidden Summoners",
  "Savage Strike",
  "The Infinity Chasers",
  "Duel Power",
  "Duelist Saga",
  "Dark Neostorm",
  "Rising Rampage",
  "Fists of the Gadgets",
  "Chaos Impact",
  "Mystic Fighters",
  "Ignition Assault",
  "Duel Overload",
  "Secret Slayers",
  "Eternity Code",
  "Toon Chaos",
  "Rise of the Duelist",
  "Phantom Rage",
  "Genesis Impact",
  "Blazing Vortex",
  "Ancient Guardians",
  "Ghosts From the Past",
  "Lightning Overdrive",
  "King's Court",
];

module.exports = {
  boosters,
};
